issues:
    exclude-rules:
        - linters:
              - gosimple
          text: "S1039:"

        # Exclude issues bypassing staticcheck.conf
        - linters:
              - staticcheck
          text: "SA1019:"

        - linters:
              - unparam
          text: "always receives"

    max-per-linter: 0
    max-same-issues: 0

linters:
    disable-all: true
    enable:
        - deadcode
        - errcheck
        - gofmt
        - gosimple
        - ineffassign
        - misspell
        - nakedret
        - staticcheck
        - structcheck
        - unconvert
        - unused
        - unparam
        - varcheck
        - vet

run:
    timeout: 10m
